baseURL = "https://scoutmastercg.com/"
languageCode = "en-us"
title = "ScoutmasterCG Archive"
theme = "ananke"

[params]
  favicon = "/favicon.svg"

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog Archive"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Podcast Archive"
    url = "/podcasts/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

  [[menu.main]]
    name = "Support"
    url = "/support/"
    weight = 5

  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 6

